[build]
  command = "npm run build:client"
  functions = "netlify/functions"
  publish = "dist/spa"

# Explicitly specify no extensions to prevent auto-installation
[extensions]

[functions]
  node_bundler = "esbuild"

# API redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# SPA fallback - serve index.html for all non-API routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
