[build]
  command = "npm run build:client"
  functions = "netlify/functions"
  publish = "dist/spa"

[functions]
  node_bundler = "esbuild"
  included_files = ["server/routes/**/*", "server/lib/**/*", "shared/**/*"]

# API redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# SPA fallback - serve index.html for all non-API routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
